function uniChar(n) {
    console.log("unichar is running");
    emojis.forEach(function(emoji, i, emojis) {
        if (emoji["short_name"] == n) {
            console.log(emoji["unified"]);
            var num = parseInt(emoji["unified"]);
            var str = emoji["unified"];
            console.log(num);
            console.log(String.fromCharCode(str));
        }
    });
}

function replace(name, index, array){
    lean_array = array.splice(index);
    new_array = lean_array.splice(index, 1, uniChar(name));
    return new_array.join("");
}

$(document).on("keypress", function() {
   
    if (event.which == 13) {
        line = editor.selection.getCursor()["row"];
    
        $(".ace_line").each(function(i, l) {
            if (line == i) {
                current = $(l).text().split(":");
                current.forEach(function(a, i, current){
                    //if (jQuery.inArray(a, names) > -1) {
                        new_string = replace(a, i, current);
                        console.log(new_string);
                    //}
                    //else {
                    //    alert ("doesn't contain");
                    //}
                });
            };
        });
    };
});

function genTable(){
	var nameToUni = {}
	for (var i=0; i < emojis.length; i++) {
		nameToUni[emojis[i].name.toLowerCase()] = emojis[i].unified;
	}
	console.log(nameToUni);
}


function genHTML(){
	classname = '"element-item free" data-category="CATEGORY""';
	category = "CATEGORY";
	htmlString = "\n";
	for (var key in emojis) {
	  if (emojiObject.hasOwnProperty(key)) {
	   
	   shortname = ":"+key.toString()+":"
	   symbol = "&#x"+emojiObject[key] +";"
	   unicode = Number("0x"+emojiObject[key]);
	string = '<button class="'+ classname + '" data-category="'+category+'">' +'\n'+'<p id="' + shortname + '">' +symbol+ '</p> '+'\n'+ '<p class="emoji">'+symbol+'</p>'+'\n'+'<p class="unicode">' + unicode + '</p> '+'\n'+' </button>'+"\n";

	console.log(string);
}
}
}



var emojis = {"aerial tramway": "1F6A1",
"airplane": "2708",
"alarm clock": "23F0",
"alien monster": "F47E","ambulance": "F691",
"american football": "F3C8",
"anchor": "2693",
"anger symbol": "F4A2","angry face": "F620",
"anguished face": "F627",
"ant": "F41C",
"antenna with bars": "F4F6",
"anticlockwise downwards and upwards open circle arrows": "F504",
"aquarius": "2652",
"aries": "2648",
"arrow pointing rightwards then curving downwards": "2935",
"arrow pointing rightwards then curving upwards": "2934",
"articulated lorry": "F69B","artist palette": "F3A8",
"astonished face": "F632",
"athletic shoe": "F45F",
"aubergine": "F346",
"automated teller machine": "F3E7",
"automobile": "F697",
"baby": "F476",
"baby angel": "F47C",
"baby bottle": "F37C",
"baby chick": "F424",
"baby symbol": "F6BC",
"back with leftwards arrow above": "F519",
"bactrian camel": "F42B",
"baggage claim": "F6C4",
"balloon": "F388",
"ballot box with check": "2611",
"banana": "F34C","bank": "F3E6",
"banknote with dollar sign": "F4B5",
"banknote with euro sign": "F4B6",
"banknote with pound sign": "F4B7",
"banknote with yen sign": "F4B4",
"bar chart": "F4CA",
"barber pole": "F488",
"baseball": "26BE",
"basketball and hoop": "F3C0","bath": "F6C0",
"bathtub": "F6C1",
"battery": "F50B",
"bear face": "F43B",
"beating heart": "F493",
"beer mug": "F37A",
"bell": "F514",
"bell with cancellation stroke": "F515",
"bento box": "F371",
"bicycle": "F6B2",
"bicyclist": "F6B4",
"bikini": "F459",
"billiards": "F3B1",
"bird": "F426",
"birthday cake": "F382",
"black club suit": "2663",
"black diamond suit": "2666",
"black down-pointing double triangle": "23EC",
"black heart suit": "2665",
"black large square": "2B1B",
"black left-pointing double triangle": "23EA",
"black left-pointing triangle": "25C0",
"black medium small square": "25FE",
"black medium square": "25FC",
"black nib": "2712",
"black question mark ornament": "2753",
"black right-pointing double triangle": "23E9",
"black right-pointing triangle": "25B6",
"black rightwards arrow": "27A1",
"black scissors": "2702",
"black small square": "25AA",
"black spade suit": "2660",
"black square button": "F532","black sun with rays": "2600",
"black telephone": "260E",
"black universal recycling symbol": "267B",
"black up-pointing double triangle": "23EB",
"blossom": "F33C","blowfish": "F421",
"blue book": "F4D8",
"blue heart": "F499",
"boar": "F417",
"bomb": "F4A3",
"bookmark": "F516",
"bookmark tabs": "F4D1",
"books": "F4DA",
"bouquet": "F490",
"bowling": "F3B3",
"boy": "F466",
"bread": "F35E",
"bride with veil": "F470",
"bridge at night": "F309",
"briefcase": "F4BC",
"broken heart": "F494",
"bug": "F41B",
"bus": "F68C",
"bus stop": "F68F",
"bust in silhouette": "F464",
"busts in silhouette": "F465",
"cactus": "F335",
"calendar": "F4C5",
"camera": "F4F7",
"cancer": "264B",
"candy": "F36C","capricorn": "2651",
"card index": "F4C7","carousel horse": "F3A0",
"carp streamer": "F38F",
"cat": "F408",
"cat face": "F431",
"cat face with tears of joy": "F639",
"cat face with wry smile": "F63C",
"chart with downwards trend": "F4C9",
"chart with upwards trend": "F4C8",
"chart with upwards trend and yen sign": "F4B9",
"cheering megaphone": "F4E3",
"chequered flag": "F3C1",
"cherries": "F352",
"cherry blossom": "F338",
"chestnut": "F330",
"chicken": "F414",
"children crossing": "F6B8",
"chocolate bar": "F36B",
"christmas tree": "F384",
"church": "26EA",
"cinema": "F3A6","circled ideograph accept": "F251",
"circled ideograph advantage": "F250",
"circled ideograph congratulation": "3297",
"circled ideograph secret": "3299",
"circled latin capital letter m": "24C2",
"circus tent": "F3AA","cityscape at dusk": "F306",
"clapper board": "F3AC",
"clapping hands sign": "F44F",
"clinking beer mugs": "F37B",
"clipboard": "F4CB",
"clock face eight oclock": "F557",
"clock face eight-thirty": "F563",
"clock face eleven oclock": "F55A",
"clock face eleven-thirty": "F566",
"clock face five oclock": "F554",
"clock face five-thirty": "F560",
"clock face four oclock": "F553",
"clock face four-thirty": "F55F",
"clock face nine oclock": "F558",
"clock face nine-thirty": "F564",
"clock face one oclock": "F550",
"clock face one-thirty": "F55C",
"clock face seven oclock": "F556",
"clock face seven-thirty": "F562",
"clock face six oclock": "F555",
"clock face six-thirty": "F561",
"clock face ten oclock": "F559",
"clock face ten-thirty": "F565",
"clock face three oclock": "F552",
"clock face three-thirty": "F55E",
"clock face twelve oclock": "F55B",
"clock face twelve-thirty": "F567",
"clock face two oclock": "F551",
"clock face two-thirty": "F55D",
"clockwise downwards and upwards open circle arrows": "F503",
"clockwise rightwards and leftwards open circle arrows": "F501",
"clockwise rightwards and leftwards open circle arrows with circled one overlay": "F502",
"closed book": "F4D5",
"closed lock with key": "F510",
"closed mailbox with lowered flag": "F4EA",
"closed mailbox with raised flag": "F4EB",
"closed umbrella": "F302",
"cloud": "2601",
"cocktail glass": "F378","collision symbol": "F4A5",
"confetti ball": "F38A",
"confounded face": "F616",
"confused face": "F615",
"construction sign": "F6A7",
"construction worker": "F477",
"convenience store": "F3EA",
"cooked rice": "F35A",
"cookie": "F36A",
"cooking": "F373",
"copyright sign": "00A9",
"couple with heart": "F491","cow": "F404",
"cow face": "F42E",
"credit card": "F4B3",
"crescent moon": "F319",
"crocodile": "F40A",
"cross mark": "274C",
"crossed flags": "F38C","crown": "F451",
"crying cat face": "F63F",
"crying face": "F622",
"crystal ball": "F52E",
"curly loop": "27B0",
"currency exchange": "F4B1","curry and rice": "F35B",
"custard": "F36E",
"customs": "F6C3",
"cyclone": "F300",
"dancer": "F483",
"dango": "F361",
"dash symbol": "F4A8",
"deciduous tree": "F333",
"delivery truck": "F69A",
"department store": "F3EC",
"diamond shape with a dot inside": "F4A0",
"direct hit": "F3AF",
"disappointed but relieved face": "F625",
"disappointed face": "F61E",
"dizzy face": "F635",
"dizzy symbol": "F4AB",
"do not litter symbol": "F6AF",
"dog": "F415",
"dog face": "F436",
"dolphin": "F42C",
"door": "F6AA",
"double curly loop": "27BF",
"double exclamation mark": "203C",
"doughnut": "F369","down-pointing red triangle": "F53B",
"down-pointing small red triangle": "F53D",
"downwards black arrow": "2B07",
"dragon": "F409","dragon face": "F432",
"dress": "F457",
"dromedary camel": "F42A",
"droplet": "F4A7",
"dvd": "F4C0",
"e-mail symbol": "F4E7",
"ear": "F442",
"ear of maize": "F33D",
"ear of rice": "F33E",
"earth globe americas": "F30E",
"earth globe asia-australia": "F30F",
"earth globe europe-africa": "F30D",
"eight pointed black star": "2734",
"eight spoked asterisk": "2733",
"electric light bulb": "F4A1","electric plug": "F50C",
"electric torch": "F526",
"elephant": "F418",
"emoji modifier fitzpatrick type-1-2": "F3FB",
"emoji modifier fitzpatrick type-3": "F3FC",
"emoji modifier fitzpatrick type-4": "F3FD",
"emoji modifier fitzpatrick type-5": "F3FE",
"emoji modifier fitzpatrick type-6": "F3FF",
"end with leftwards arrow above": "F51A",
"envelope": "2709",
"envelope with downwards arrow above": "F4E9","european castle": "F3F0",
"european post office": "F3E4",
"evergreen tree": "F332",
"exclamation question mark": "2049",
"expressionless face": "F611","extraterrestrial alien": "F47D",
"eyeglasses": "F453",
"eyes": "F440",
"face massage": "F486",
"face savouring delicious food": "F60B",
"face screaming in fear": "F631",
"face throwing a kiss": "F618",
"face with cold sweat": "F613",
"face with look of triumph": "F624",
"face with medical mask": "F637",
"face with no good gesture": "F645",
"face with ok gesture": "F646",
"face with open mouth": "F62E",
"face with open mouth and cold sweat": "F630",
"face with stuck-out tongue": "F61B",
"face with stuck-out tongue and tightly-closed eyes": "F61D",
"face with stuck-out tongue and winking eye": "F61C",
"face with tears of joy": "F602",
"face without mouth": "F636",
"factory": "F3ED",
"fallen leaf": "F342",
"family": "F46A",
"father christmas": "F385",
"fax machine": "F4E0",
"fearful face": "F628",
"ferris wheel": "F3A1",
"file folder": "F4C1",
"fire": "F525",
"fire engine": "F692",
"firework sparkler": "F387",
"fireworks": "F386",
"first quarter moon symbol": "F313",
"first quarter moon with face": "F31B",
"fish": "F41F",
"fish cake with swirl design": "F365",
"fishing pole and fish": "F3A3",
"fisted hand sign": "F44A",
"flag in hole": "26F3",
"flexed biceps": "F4AA","floppy disk": "F4BE",
"flower playing cards": "F3B4",
"flushed face": "F633",
"foggy": "F301",
"footprints": "F463",
"fork and knife": "F374",
"fountain": "26F2",
"four leaf clover": "F340","french fries": "F35F",
"fried shrimp": "F364",
"frog face": "F438",
"front-facing baby chick": "F425",
"frowning face with open mouth": "F626",
"fuel pump": "26FD",
"full moon symbol": "F315","full moon with face": "F31D",
"game die": "F3B2",
"gem stone": "F48E",
"gemini": "264A",
"ghost": "F47B","girl": "F467",
"globe with meridians": "F310",
"glowing star": "F31F",
"goat": "F410",
"graduation cap": "F393",
"grapes": "F347",
"green apple": "F34F",
"green book": "F4D7",
"green heart": "F49A",
"grimacing face": "F62C",
"grinning cat face with smiling eyes": "F638",
"grinning face": "F600",
"grinning face with smiling eyes": "F601",
"growing heart": "F497",
"guardsman": "F482",
"guitar": "F3B8",
"haircut": "F487",
"hamburger": "F354",
"hammer": "F528",
"hamster face": "F439",
"handbag": "F45C",
"happy person raising one hand": "F64B",
"hash key": "0023-",
"20E3hatching chick": "F423",
"headphone": "F3A7",
"hear-no-evil monkey": "F649",
"heart decoration": "F49F",
"heart with arrow": "F498",
"heart with ribbon": "F49D",
"heavy black heart": "2764",
"heavy check mark": "2714",
"heavy division sign": "2797",
"heavy dollar sign": "F4B2","heavy exclamation mark symbol": "2757",
"heavy large circle": "2B55",
"heavy minus sign": "2796",
"heavy multiplication x": "2716",
"heavy plus sign": "2795",
"helicopter": "F681","herb": "F33F",
"hibiscus": "F33A",
"high brightness symbol": "F506",
"high voltage sign": "26A1",
"high-heeled shoe": "F460","high-speed train": "F684",
"high-speed train with bullet nose": "F685",
"hocho": "F52A",
"honey pot": "F36F",
"honeybee": "F41D",
"horizontal traffic light": "F6A5",
"horse": "F40E",
"horse face": "F434",
"horse racing": "F3C7",
"hospital": "F3E5",
"hot beverage": "2615",
"hot springs": "2668",
"hotel": "F3E8","hourglass": "231B",
"hourglass with flowing sand": "23F3",
"house building": "F3E0","house with garden": "F3E1",
"hundred points symbol": "F4AF",
"hushed face": "F62F",
"ice cream": "F368",
"imp": "F47F",
"inbox tray": "F4E5",
"incoming envelope": "F4E8",
"information desk person": "F481",
"information source": "2139",
"input symbol for latin capital letters": "F520","input symbol for latin letters": "F524",
"input symbol for latin small letters": "F521",
"input symbol for numbers": "F522",
"input symbol for symbols": "F523",
"izakaya lantern": "F3EE",
"jack-o-lantern": "F383",
"japanese castle": "F3EF",
"japanese dolls": "F38E",
"japanese goblin": "F47A",
"japanese ogre": "F479",
"japanese post office": "F3E3",
"japanese symbol for beginner": "F530",
"jeans": "F456",
"key": "F511",
"keycap 0": "0030-",
"20E3keycap 1": "0031-",
"20E3keycap 2": "0032-",
"20E3keycap 3": "0033-",
"20E3keycap 4": "0034-",
"20E3keycap 5": "0035-",
"20E3keycap 6": "0036-",
"20E3keycap 7": "0037-",
"20E3keycap 8": "0038-",
"20E3keycap 9": "0039-",
"20E3keycap ten": "F51F",
"kimono": "F458",
"kiss": "F48F",
"kiss mark": "F48B",
"kissing cat face with closed eyes": "F63D",
"kissing face": "F617",
"kissing face with closed eyes": "F61A",
"kissing face with smiling eyes": "F619",
"koala": "F428",
"lady beetle": "F41E",
"large blue circle": "F535",
"large blue diamond": "F537",
"large orange diamond": "F536",
"large red circle": "F534",
"last quarter moon symbol": "F317",
"last quarter moon with face": "F31C",
"leaf fluttering in wind": "F343",
"ledger": "F4D2",
"left luggage": "F6C5",
"left right arrow": "2194",
"left-pointing magnifying glass": "F50D","leftwards arrow with hook": "21A9",
"leftwards black arrow": "2B05",
"lemon": "F34B","leo": "264C",
"leopard": "F406","libra": "264E",
"light rail": "F688","link symbol": "F517",
"lipstick": "F484",
"lock": "F512",
"lock with ink pen": "F50F",
"lollipop": "F36D",
"loudly crying face": "F62D",
"love hotel": "F3E9",
"love letter": "F48C",
"low brightness symbol": "F505",
"mahjong tile red dragon": "F004",
"man": "F468",
"man and woman holding hands": "F46B",
"man with gua pi mao": "F472",
"man with turban": "F473",
"mans shoe": "F45E",
"maple leaf": "F341",
"meat on bone": "F356",
"medium black circle": "26AB",
"medium white circle": "26AA",
"melon": "F348","memo": "F4DD",
"mens symbol": "F6B9",
"metro": "F687",
"microphone": "F3A4",
"microscope": "F52C",
"milky way": "F30C",
"minibus": "F690",
"minidisc": "F4BD",
"mobile phone": "F4F1",
"mobile phone off": "F4F4",
"mobile phone with rightwards arrow at left": "F4F2",
"money bag": "F4B0",
"money with wings": "F4B8",
"monkey": "F412",
"monkey face": "F435",
"monorail": "F69D",
"moon viewing ceremony": "F391",
"mount fuji": "F5FB",
"mountain bicyclist": "F6B5",
"mountain cableway": "F6A0",
"mountain railway": "F69E",
"mouse": "F401",
"mouse face": "F42D",
"mouth": "F444",
"movie camera": "F3A5",
"moyai": "F5FF",
"multiple musical notes": "F3B6",
"mushroom": "F344",
"musical keyboard": "F3B9",
"musical note": "F3B5",
"musical score": "F3BC",
"nail polish": "F485",
"name badge": "F4DB",
"necktie": "F454",
"negative squared ab": "F18E",
"negative squared cross mark": "274E",
"negative squared latin capital letter a": "F170","negative squared latin capital letter b": "F171",
"negative squared latin capital letter o": "F17E",
"negative squared latin capital letter p": "F17F",
"neutral face": "F610",
"new moon symbol": "F311",
"new moon with face": "F31A",
"newspaper": "F4F0",
"night with stars": "F303",
"no bicycles": "F6B3",
"no entry": "26D4",
"no entry sign": "F6AB","no mobile phones": "F4F5",
"no one under eighteen symbol": "F51E",
"no pedestrians": "F6B7",
"no smoking symbol": "F6AD",
"non-potable water symbol": "F6B1",
"north east arrow": "2197",
"north west arrow": "2196",
"nose": "F443","notebook": "F4D3",
"notebook with decorative cover": "F4D4",
"nut and bolt": "F529",
"octopus": "F419",
"oden": "F362",
"office building": "F3E2",
"ok hand sign": "F44C",
"older man": "F474",
"older woman": "F475",
"on with exclamation mark with left right arrow above": "F51B",
"oncoming automobile": "F698",
"oncoming bus": "F68D",
"oncoming police car": "F694",
"oncoming taxi": "F696",
"open book": "F4D6",
"open file folder": "F4C2",
"open hands sign": "F450",
"open lock": "F513",
"open mailbox with lowered flag": "F4ED",
"open mailbox with raised flag": "F4EC",
"ophiuchus": "26CE",
"optical disc": "F4BF","orange book": "F4D9",
"outbox tray": "F4E4",
"ox": "F402",
"package": "F4E6",
"page facing up": "F4C4",
"page with curl": "F4C3",
"pager": "F4DF",
"palm tree": "F334",
"panda face": "F43C",
"paperclip": "F4CE",
"part alternation mark": "303D",
"party popper": "F389","passport control": "F6C2",
"paw prints": "F43E",
"peach": "F351",
"pear": "F350",
"pedestrian": "F6B6",
"pencil": "270F",
"penguin": "F427","pensive face": "F614",
"performing arts": "F3AD",
"persevering face": "F623",
"person bowing deeply": "F647",
"person frowning": "F64D",
"person raising both hands in celebration": "F64C",
"person with blond hair": "F471",
"person with folded hands": "F64F",
"person with pouting face": "F64E",
"personal computer": "F4BB",
"pig": "F416",
"pig face": "F437",
"pig nose": "F43D",
"pile of poo": "F4A9",
"pill": "F48A",
"pine decoration": "F38D",
"pineapple": "F34D",
"pisces": "2653",
"pistol": "F52B","playing card black joker": "F0CF",
"police car": "F693",
"police cars revolving light": "F6A8",
"police officer": "F46E",
"poodle": "F429",
"postal horn": "F4EF",
"postbox": "F4EE",
"pot of food": "F372",
"potable water symbol": "F6B0",
"pouch": "F45D",
"poultry leg": "F357",
"pouting cat face": "F63E",
"pouting face": "F621",
"princess": "F478",
"public address loudspeaker": "F4E2",
"purple heart": "F49C",
"purse": "F45B",
"pushpin": "F4CC",
"put litter in its place symbol": "F6AE",
"rabbit": "F407",
"rabbit face": "F430",
"radio": "F4FB",
"radio button": "F518",
"railway car": "F683",
"rainbow": "F308",
"raised fist": "270A",
"raised hand": "270B",
"ram": "F40F","rat": "F400",
"recreational vehicle": "F699",
"red apple": "F34E",
"regional indicator symbol letters ae": "F1E6",
"-1F1EAregional indicator symbol letters at": "F1E6",
"-1F1F9regional indicator symbol letters au": "F1E6",
"-1F1FAregional indicator symbol letters be": "F1E7",
"-1F1EAregional indicator symbol letters br": "F1E7",
"-1F1F7regional indicator symbol letters ca": "F1E8",
"-1F1E6regional indicator symbol letters ch": "F1E8",
"-1F1EDregional indicator symbol letters cl": "F1E8",
"-1F1F1regional indicator symbol letters cn": "F1E8",
"-1F1F3regional indicator symbol letters co": "F1E8",
"-1F1F4regional indicator symbol letters de": "F1E9",
"-1F1EAregional indicator symbol letters dk": "F1E9",
"-1F1F0regional indicator symbol letters es": "F1EA",
"-1F1F8regional indicator symbol letters fi": "F1EB",
"-1F1EEregional indicator symbol letters fr": "F1EB",
"-1F1F7regional indicator symbol letters gb": "F1EC",
"-1F1E7regional indicator symbol letters hk": "F1ED",
"-1F1F0regional indicator symbol letters id": "F1EE",
"-1F1E9regional indicator symbol letters ie": "F1EE",
"-1F1EAregional indicator symbol letters il": "F1EE",
"-1F1F1regional indicator symbol letters in": "F1EE",
"-1F1F3regional indicator symbol letters it": "F1EE",
"-1F1F9regional indicator symbol letters jp": "F1EF",
"-1F1F5regional indicator symbol letters kr": "F1F0",
"-1F1F7regional indicator symbol letters mo": "F1F2",
"-1F1F4regional indicator symbol letters mx": "F1F2",
"-1F1FDregional indicator symbol letters my": "F1F2",
"-1F1FEregional indicator symbol letters nl": "F1F3",
"-1F1F1regional indicator symbol letters no": "F1F3",
"-1F1F4regional indicator symbol letters nz": "F1F3",
"-1F1FFregional indicator symbol letters ph": "F1F5",
"-1F1EDregional indicator symbol letters pl": "F1F5",
"-1F1F1regional indicator symbol letters pr": "F1F5",
"-1F1F7regional indicator symbol letters pt": "F1F5",
"-1F1F9regional indicator symbol letters ru": "F1F7",
"-1F1FAregional indicator symbol letters sa": "F1F8",
"-1F1E6regional indicator symbol letters se": "F1F8",
"-1F1EAregional indicator symbol letters sg": "F1F8",
"-1F1ECregional indicator symbol letters tr": "F1F9",
"-1F1F7regional indicator symbol letters us": "F1FA",
"-1F1F8regional indicator symbol letters vn": "F1FB",
"-1F1F3regional indicator symbol letters za": "F1FF",
"-1F1E6registered sign": "00AE",
"relieved face": "F60C","restroom": "F6BB",
"revolving hearts": "F49E",
"ribbon": "F380",
"rice ball": "F359",
"rice cracker": "F358",
"right-pointing magnifying glass": "F50E",
"rightwards arrow with hook": "21AA",
"ring": "F48D","roasted sweet potato": "F360",
"rocket": "F680",
"roller coaster": "F3A2",
"rooster": "F413",
"rose": "F339",
"round pushpin": "F4CD",
"rowboat": "F6A3",
"rugby football": "F3C9",
"runner": "F3C3",
"running shirt with sash": "F3BD",
"sagittarius": "2650",
"sailboat": "26F5",
"sake bottle and cup": "F376","satellite antenna": "F4E1",
"saxophone": "F3B7",
"school": "F3EB",
"school satchel": "F392",
"scorpius": "264F",
"scroll": "F4DC","seat": "F4BA",
"see-no-evil monkey": "F648",
"seedling": "F331",
"shaved ice": "F367",
"sheep": "F411",
"ship": "F6A2",
"shooting star": "F320",
"shortcake": "F370",
"shower": "F6BF",
"silhouette of japan": "F5FE",
"six pointed star with middle dot": "F52F",
"ski and ski boot": "F3BF",
"skull": "F480",
"sleeping face": "F634",
"sleeping symbol": "F4A4",
"sleepy face": "F62A",
"slice of pizza": "F355",
"slot machine": "F3B0",
"small blue diamond": "F539",
"small orange diamond": "F538",
"smiling cat face with heart-shaped eyes": "F63B",
"smiling cat face with open mouth": "F63A",
"smiling face with halo": "F607",
"smiling face with heart-shaped eyes": "F60D",
"smiling face with horns": "F608",
"smiling face with open mouth": "F603",
"smiling face with open mouth and cold sweat": "F605",
"smiling face with open mouth and smiling eyes": "F604",
"smiling face with open mouth and tightly-closed eyes": "F606",
"smiling face with smiling eyes": "F60A",
"smiling face with sunglasses": "F60E",
"smirking face": "F60F",
"smoking symbol": "F6AC",
"snail": "F40C",
"snake": "F40D",
"snowboarder": "F3C2",
"snowflake": "2744",
"snowman without snow": "26C4",
"soccer ball": "26BD",
"soft ice cream": "F366","soon with rightwards arrow above": "F51C",
"south east arrow": "2198",
"south west arrow": "2199",
"spaghetti": "F35D","sparkle": "2747",
"sparkles": "2728",
"sparkling heart": "F496","speak-no-evil monkey": "F64A",
"speaker": "F508",
"speaker with cancellation stroke": "F507",
"speaker with one sound wave": "F509",
"speaker with three sound waves": "F50A",
"speech balloon": "F4AC",
"speedboat": "F6A4",
"spiral shell": "F41A",
"splashing sweat symbol": "F4A6",
"spouting whale": "F433",
"squared cjk unified ideograph-6e80": "F235",
"squared cjk unified ideograph-7a7a": "F233",
"squared cjk unified ideograph-55b6": "F23A",
"squared cjk unified ideograph-5272": "F239",
"squared cjk unified ideograph-5408": "F234",
"squared cjk unified ideograph-6307": "F22F",
"squared cjk unified ideograph-6708": "F237",
"squared cjk unified ideograph-6709": "F236",
"squared cjk unified ideograph-7121": "F21A",
"squared cjk unified ideograph-7533": "F238",
"squared cjk unified ideograph-7981": "F232",
"squared cl": "F191",
"squared cool": "F192",
"squared free": "F193",
"squared id": "F194",
"squared katakana koko": "F201",
"squared katakana sa": "F202",
"squared new": "F195",
"squared ng": "F196",
"squared ok": "F197",
"squared sos": "F198",
"squared up with exclamation mark": "F199",
"squared vs": "F19A",
"station": "F689",
"statue of liberty": "F5FD",
"steam locomotive": "F682",
"steaming bowl": "F35C",
"straight ruler": "F4CF",
"strawberry": "F353",
"sun behind cloud": "26C5",
"sun with face": "F31E","sunflower": "F33B",
"sunrise": "F305",
"sunrise over mountains": "F304",
"sunset over buildings": "F307",
"surfer": "F3C4",
"sushi": "F363",
"suspension railway": "F69F",
"swimmer": "F3CA",
"syringe": "F489",
"t-shirt": "F455",
"tanabata tree": "F38B",
"tangerine": "F34A",
"taurus": "2649",
"taxi": "F695","teacup without handle": "F375",
"tear-off calendar": "F4C6",
"telephone receiver": "F4DE",
"telescope": "F52D",
"television": "F4FA",
"tennis racquet and ball": "F3BE",
"tent": "26FA",
"thought balloon": "F4AD","thumbs down sign": "F44E",
"thumbs up sign": "F44D",
"ticket": "F3AB",
"tiger": "F405",
"tiger face": "F42F",
"tired face": "F62B",
"toilet": "F6BD",
"tokyo tower": "F5FC",
"tomato": "F345",
"tongue": "F445",
"top hat": "F3A9",
"top with upwards arrow above": "F51D",
"tractor": "F69C",
"trade mark sign": "2122",
"train": "F686","tram": "F68A",
"tram car": "F68B",
"triangular flag on post": "F6A9",
"triangular ruler": "F4D0",
"trident emblem": "F531",
"trolleybus": "F68E",
"trophy": "F3C6",
"tropical drink": "F379",
"tropical fish": "F420",
"trumpet": "F3BA",
"tulip": "F337",
"turtle": "F422",
"twisted rightwards arrows": "F500",
"two hearts": "F495",
"two men holding hands": "F46C",
"two women holding hands": "F46D",
"umbrella with rain drops": "2614",
"unamused face": "F612","up down arrow": "2195",
"up-pointing red triangle": "F53A","up-pointing small red triangle": "F53C",
"upwards black arrow": "2B06",
"vertical traffic light": "F6A6","vibration mode": "F4F3",
"victory hand": "270C",
"video camera": "F4F9","video game": "F3AE",
"videocassette": "F4FC",
"violin": "F3BB",
"virgo": "264D",
"volcano": "F30B","waning crescent moon symbol": "F318",
"waning gibbous moon symbol": "F316",
"warning sign": "26A0",
"watch": "231A",
"water buffalo": "F403","water closet": "F6BE",
"water wave": "F30A",
"watermelon": "F349",
"waving hand sign": "F44B",
"wavy dash": "3030",
"waxing crescent moon symbol": "F312","waxing gibbous moon symbol": "F314",
"weary cat face": "F640",
"weary face": "F629",
"wedding": "F492",
"whale": "F40B",
"wheelchair symbol": "267F",
"white down pointing backhand index": "F447","white exclamation mark ornament": "2755",
"white flower": "F4AE","white heavy check mark": "2705",
"white large square": "2B1C",
"white left pointing backhand index": "F448","white medium small square": "25FD",
"white medium square": "25FB",
"white medium star": "2B50",
"white question mark ornament": "2754",
"white right pointing backhand index": "F449","white small square": "25AB",
"white smiling face": "263A",
"white square button": "F533","white up pointing backhand index": "F446",
"white up pointing index": "261D",
"wind chime": "F390","wine glass": "F377",
"winking face": "F609",
"wolf face": "F43A",
"woman": "F469",
"woman with bunny ears": "F46F",
"womans boots": "F462",
"womans clothes": "F45A",
"womans hat": "F452",
"womans sandal": "F461",
"womens symbol": "F6BA",
"worried face": "F61F",
"wrapped present": "F381",
"wrench": "F527",
"yellow heart": "F49B"}

var emojiObject = JSON.parse(JSON.stringify(emojis));

//function uniChar(n) {
//    var result = n;
//    try {
//        var num = parseInt(emojis[n], 16);
//        result = String.fromCharCode(num);
//        return result;
//    }
//    catch(e) {
//        return n;
//    }
//}
//
//function replace(name, index, array){
//    array.splice(index, 1);
//    array.splice(index, 0, uniChar(name));
//}

$(document).on("keypress", function() {
    if (event.which == 13) {
        for (key in emojiObject) {
            editor.find(":" + key + ":");
            editor.replace(emojione.toImage(key));
//            editor.replace(String.fromCharCode(parseInt(emojiObject[key], 16)));
        }
        




//        line = editor.selection.getCursor()["row"];
//        current = $(line).text().split(":");
//        $(".ace_line").each(function(i, l) {
//            if (line == i) {
//                current = $(l).text().split(":");
//                for (i=0; i<current.length; i++) {
//                    replace(current[i], i, current);
//                };
//                content = current.join("");
//                $(l).empty();
//                console.log(l);
//                $(l).html(content);
//            };
//        });
    };
});

function genTable(){
	var nameToUni = {}
	for (var i=0; i < emojis.length; i++) {
		nameToUni[emojis[i].name.toLowerCase()] = emojis[i].unified;
	}
	console.log(nameToUni);
}



